spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mariadb://localhost:3306/board
    username: root
    password: 1q2w3e4r!@
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
    defer-datasource-initialization: true
    #properties:
      #hibernate:
        #format_sql: true

logging:
  level:
    p6spy: info

#p6spy query logging
decorator:
  datasource:
    p6spy:
      enable-logging: true
    #logging:
  #level:
    #org.springframework: INFO
    #org.hibernate.sql: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE

json:
  path: /upload/data/

  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html

springdoc:
  swagger-ui:
    path: /swagger-ui.html

